version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: sql
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
